# Generated by Django 4.2.7 on 2023-11-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Urgent', 'Urgent'), ('Closed', 'Closed'), ('Resolved', 'Resolved')], default='Open', max_length=10),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Urgent', 'Urgent'), ('Closed', 'Closed'), ('Resolved', 'Resolved')], default='Open', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.report')),
            ],
        ),
    ]
